allenhwkim/angularjs-google-maps

- app/scripts/directives/drawing-manager.js
- app/scripts/services/attr2_options.js
- testapp/drawing-manager.html
add drawing manager library from Google Maps
> Add drawing manager library

- app/scripts/services/maps_js_loader.js
the lines in question were breaking the minified js file due to no annotations. Here is a hotfix.
> annotate code for minification

- app/scripts/directives/info-window.js
Hey, I really like the way this wrapper library is written. Its clean, concise and well documented. I had been using angular-google-maps until today and in the end I just found it too bloated, unintuitive and buggy.
Anyway, I noticed a couple of things in the source I thought I'd clean up given the quality of the code so far. No functionality should be affected here, its just some line indentation and removal of redundant code.
We're looking to use this in a production app (not public facing), so I'm happy to make what contributions I can.
Cheers!
> Housekeeping

- directives/map.js
- directives/map_controller.js
- services/navigator_geolocation.js
I have a problem; i don't know hoe to make the new parameter can receive an Object (now is received as a strin representation)
Description: The navigator geolocations options. i.e. { maximumAge: 3000, timeout:
5000, enableHighAccuracy: true }. If none specified, { timeout: 5000 }.
If timeout not specified, timeout: 5000 added
> Added a new option (geo-location-options)

- testapp/map_with_current_position.html
There is a space missing in console statement
> Add missing space

- services/geo_coder.js
- spec/services/geo_coder_spec.js
Not a huge change as mentioned in the issue but I believe it might be easier to track errors.
>  Changed return value for the Geocoder promise failure.

- controllers/map-controller.js
- directives/bicycling-layer.js
- directives/custom-control.js
- directives/custom-marker.js
- directives/directions.js
- directives/drawing-manager.js
- directives/dynamic-maps-engine-layer.js
- directives/fusion-tables-layer.js
- directives/heatmap-layer.js
- directives/info-window.js
- directives/kml-layer.js
- directives/map-data.js
- directives/map-type.js
- directives/maps-engine-layer.js
- directives/marker.js
- directives/places-auto-complete.js
- directives/shape.js
- directives/street-view-panorama.js
- directives/traffic-layer.js
- directives/transit-layer.js
- services/attr2-map-options.js
- testapp/street-view-panorama.html
At least for the "street-view-panorama" directive and the "ng-map"
directive, dynamically bounded values weren't evaluated. Right now the
scope is being passed along so it helps parsing those values. #413 
There are probably other places this fix should be applied to considering other directives are using "Attr2MapOptions". Perhaps my implementation isn't even proper to begin with, so let me know how I can change it accordingly.
I can at least use this custom build for my project.
> Dynamically bounded values weren't evaluated properly

- build/scripts/ng-map.js
Changed Gogole to Google in several lines.
> Comment typo

- services/attr2-map-options.js
more info: https://developers.google.com/maps/documentation/javascript/3.exp/reference#Icon
> support labelOrigin parameter for marker icons

- README.md
update readme to include a link to be used with meteor
> link to meteor package

- package.js
Added a meteor package file to be published on atmospherejs. 
If you have a meteor developer account, change the package name to your account. 
you can find more about it here: 
http://www.angular-meteor.com/tutorials/socially/angular1/3rd-party-libraries
> meteor package

- directives/map-lazy-load.js
http://plnkr.co/edit/aKWhebavs9IGg3XXwo8D?p=preview
> [map-lazy-load] keep element content for each calls.

- directives/places-auto-complete.js
watch 'component-restrictions' attribute to trigger country's filter
dynamically
> places-auto-complete filter by country dynamically

- gulpfile.js
+ this splits gulp build js tasks
This generates additional build/scripts/ng-map.no-dependency.js which is almost the same as  build/scripts/ng-map.js but without "require(angular)" 
With this webpack can be easily configured to work with ngMap.
This should resolve https://github.com/allenhwkim/angularjs-google-maps/issues/692 and
https://github.com/allenhwkim/angularjs-google-maps/issues/692
The other way is to just drop require("angular") completely in gulp build and suspect that angular is defined which is common behaviour for ng apps.
> provide version without angular require dependency

- testapp/polyline-simple.html
Reverts allenhwkim/angularjs-google-maps#731
sorry, i'm mistake.
> Revert "Fix tag"

- testapp/custom-marker-2.html
Do not merge before January 20, 2017.
> Updating example for state of affairs

- directives/custom-control.js
> Replace compile innerHTML by transclusion with transclude for custom control

- directives/map-data.js
> Pass map.id to getMap() in map-data

- testapp/marker_with_ng_repeat_no_watcher.html
I've found that checkbox draggable is not used.
> testapp: use checkbox to change draggable

- directives/directions.js
> directions directive does not honour no-watcher
