app/scripts/directives/map-lazy-load.js
* if url contain `?` (key, version...) then url generate is wrong
* load multiple time google map js
=> Fix lazy loading bugs

app/scripts/directives/map-lazy-load.js
In test context (jasmine), the directive don't reload map because the directive is already compiled but the google object was garbage collected.
=> Better check of the google map already loaded in lazyload directive

app/scripts/directives/directions.js
This is important when an user have more dynamic directives with ng-if or similars.
=> Added $destroy event to delete directions directive when has been removed

app/scripts/services/attr2_options.js, spec/services/attr2_options_spec.js
The current behaviour is that event handlers will be
passed the value of each argument as it was at the time
the event handler was created, which is when the
directive is linked. This means an event handler being
passed args derived from the scope will not receive
any updated values.
This commit will alter the behaviour to send through
any updated model values.
=> fix(events): pass through updated model values

services/attr2_options.js, spec/services/attr2_options_spec.js
See the issue here: http://jsfiddle.net/rjnqdLhf/1/
- According to Google's Maps API, the directions request can have a transitOptions property. This transitOptions object an have departureTime/arrivalTime property, which are expected to be Date objects.
- When passing the transitOptions object as an attribute to the directions directive, angular converts this date object to a string. This results in a request error when the Directions Request is made to the Google API.
-- The suggested solution remedies this error by passing JSON objects back through getOptions in Attr2Options, changing nested objects to Google API options using toOptionValue.
=> bugfix to convert date in options hash to a Date object in Directions Request

package.json
These two dependencies were moved to devDevependencies. In its current state this causes `jspm` to install all of `gulp` and `glob`'s dependencies as well.
=> Removed `gulp` and `glob` as dependencies

README.md
If user has the module installed, they are referencing that instead of the externally hosted one.
=> Remove external script reference

controllers/map-controller.js
Contains the fix that was missing from this bug since the latest pull-request: https://github.com/allenhwkim/angularjs-google-maps/issues/413
=> Evanluate map fix

testapp/infowindow_ng_click.html
In this demo all info windows appear always on the marker named "foo". Using the clicked marker's id in showDetail makes it appears on the right marker.
=> Fix for info window appearing on wrong marker

directives/info-window.js
Hello, 
I'm using custom markers (with dynamic ids) with info windows but there is no way to open info windows from custom markers, because the code does only check the markers object.
```html
<custom-marker ng-repeat="device in vm.devices"
id='device-marker-{{device.id}}'
on-click="alarmCtrl.showDeviceDetail(device);"
position="[{{device.position.lat}}, {{ device.position.lon }}]">
```
```javascript
this.showDeviceDetail = function (e, objDevice) {
vm.map.showInfoWindow('device-detail', "device-marker-" + objDevice.id);
};
```
I need to make use of the dynamic ids, because i want to open the  info windows from the code in different locations.
Tests did pass
=> Enable customMarkers to open Info Windows (by id)

controllers/map-controller.js, directives/map.js
The ability to trigger resize needs to be in the initialize map function.  The main controller does not know when the map is ready for a resize and so it is a guessing game with setTimeout.  This adds the ability to do <ng-map trigger-resize="true"
=> Add trigger resize to map initialization

services/ng-map.js
To reproduce the issue just try to destroy a map with `lazy-init="true"` and is not yet initialized:
```
TypeError: Cannot read property 'forEach' of undefined
at Object.deleteMap
```
=> [deleteMap] clear controllers only when is it defined

services/ng-map.js
I am not sure if you are keeping the heat map data around to be reused or not but in my application it is rendering a new heatmap on top of the previous one.  If this is intended you can close.
=> Remove Heatmap Layers when map is deleted

controllers/map-controller.js
I want to use lazy init with dynamic map ids, but currently the map id is just read from the attribute rather than parsed in the scope if the map is initialized lazily. This did the trick for me, hopefully its something others would want to
=> parsing handlebars expressions in ids before lazy init

controllers/map-controller.js
Currently when you have no markers the zoom-to-include-markers centers the map around geo coordinate 0,0 (at least I guess), see: http://plnkr.co/edit/uiif3eISQM1fg3kknvaz?p=preview for an example. This looks a bit weird if you init the map without markers or remove the markers after initialization.
This pull request makes sure that if you have no markers the default center location is used.
=> Updated zoomToIncludeMarkers to only fit to bounds if there are markers

testapp/map-lazy-load-params.html
I was using this option, trying to affect loading behavior and banging my head against the wall until I saw it was removed from the service.
I didn't understand from the commit comment why it was removed, but hopefully this should prevent someone else from trying to use it.
=> Remove deprecated timeout option from example

directives/info-window.js, testapp/infowindow-template.html, testapp/partials/custom-info-window-template.html
This feature will allow you to have the content from the info window loaded from an external template using the ```$templateCache```.
I needed this method because I wrapped ```ng-map``` inside my own directive that serves as a reusable component. Dynamic template content turned out to be hard and this was the only way I could make this work as far as I know.
A demo can be viewed from file ```infowindow-template.html```.
=> New feature: Info window external template

controllers/map-controller.js
IE < 12 fails with the startsWith and endsWith lines (not supported).
See https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
This change replaces the methods with logic that works in all browsers.
=> startsWith and endsWith are not supported in IE < 12

directives/custom-marker.js
Moved calculation of final pixel coordinates for custom markers to the moment these are applied to the overlay's element to account for any changes in size that may occur during the 300ms of delay that this function has under some circumstances (Line 85).
=> Fix for issue #670 "Custom markers disappear on second load"

README.md
When I first saw the documentation, I thought the module was added to bower, not in npm. To avoid that confusion, added the npm install command in docs.
=> Add the npm  install in docs

directives/custom-marker.js
- Return from setPosition if getProjection() returns null.
-Solves issue where a marker clusterer removes markers from the map and getProjection().fromLatLnToPixel() throws a TypeError
=> Custom Marker Directive - return from setPosition

directives/fusion-tables-layer.js
Fixes fusion-tables-layer not being removed with ng-if
=> Allow fusion-tables-layer to be removed from map

gulpfile.js, spec/services/ng-map-pool-spec.js
Note: this doesn’t fix any tests but stops some incidental errors from
running `gulp test`
- Update initialisation of karma as per
https://github.com/karma-runner/gulp-karma. Avoids a deprecation
warning.
- Remove initialisation of global google object in ng-map-pool-spec. I
confess I don’t know what this is trying to achieve but it caused this
error “TypeError: undefined is not a constructor (evaluating
'google.maps.__gjsload__’)”. And this triggered “Unhandled rejection
Error” during PhantomJS shutdown.
=> Updates to Test Harness

directives/custom-control.js
My team ran into an issue with this customControl directive, where its transclusion template was getting overwritten, causing multiple instances of elements that should not have been duplicated.
For context, this happened in cases where the parent component, whose template included a `<custom-control></custom-control>` element, would initially be rendered, then would be destroyed (thanks to an ngIf condition), then be rendered a second time. When rendered the second time, the transclusion template would include duplicates of every element it contained.
This also held true if the process was repeated a third time (3 instances of each element in the template), a fourth time, and so on.
The code in this PR prevents the transclusion template from getting overwritten and duplicated.
=> Fixed issue that can cause the transclusion template to be overwritten.

README.md
the old URL below will lead to "Page not found" 
https://github.com/ng2-ui/ng2-maps
=> ReadMe url update

directives/heatmap-layer.js
Allows to the directive access to a nested property.
This problem happens when we are using a nested property like 'data.map.heathData' or more commonly when we are using the syntax 'controllerAs', adding a 'vm' variable or similar.
fix: https://github.com/allenhwkim/angularjs-google-maps/issues/835
=> Fix heatmap-layer.js nested prop
